package org.greenGroup.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DBUtils {

    PropertyUtils propertyUtils = new PropertyUtils("app.properties");
    private static DBUtils db = null;
    private final String url = propertyUtils.getProperty("db.url");
    private final String user = propertyUtils.getProperty("db.login");
    private final String password = propertyUtils.getProperty("db.password");

    private final Connection connection;

    static {
        loadDriver();
    }

    private static void loadDriver() {
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException();
        }
    }

    public static DBUtils createDB() {
        if (db == null) {
            db = new DBUtils();
        }
        return db;
    }

    private DBUtils() {
        connection = getConnection();
        createUsersTable();
    }

    public Connection getConnection() {
        Connection con = null;
        try {
            con = DriverManager.getConnection(url, user, password);
            con.setAutoCommit(true);
        } catch (SQLException e) {
            System.err.println("Failed to get connection with db, check the url" + e.getMessage());
        } finally {
            return con;
        }
    }

    public void createUsersTable() {
        try (Statement statement = connection.createStatement()) {
            String sql = "CREATE TABLE USERS ("
                    + "     ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,"
                    + "     FIRST_NAME VARCHAR(24) NOT NULL, "
                    + "     LAST_NAME VARCHAR(24) NOT NULL, "
                    + "     AGE INTEGER NOT NULL "
                    + ");";
            statement.executeUpdate(sql);
        } catch (SQLException e) {
            e.getStackTrace();
        }
    }
}
