package org.greenGroup.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DBUtils {
    private static DBUtils db = null;

    public static DBUtils createDB() {
        if (db == null) {
            db = new DBUtils();
        }
        return db;
    }

    private DBUtils() {
        createUsersTable();
    }


    public void createUsersTable() {
        try (Connection connection = ConnectionCreator.createConnection();
             Statement statement = connection.createStatement()) {
            String sql = "CREATE TABLE USERS ("
                    + "     ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,"
                    + "     FIRST_NAME VARCHAR(24) NOT NULL, "
                    + "     LAST_NAME VARCHAR(24) NOT NULL, "
                    + "     AGE INTEGER NOT NULL "
                    + ");";
            statement.executeUpdate(sql);
        } catch (SQLException e) {
            e.getStackTrace();
        }
    }
}
